In [17]:
import numpy as np

In [19]:
import numpy as np

print(np.__version__)


1.21.5


In [20]:
import numpy as np
print(np.__version__)

1.21.5


## Advertisment sale prediction from an existing customer.

Finding the probrem - Application 
predicting whether this new customer, will buy this products or not

## Logistic Regression


In [21]:
import pandas as pd

In [24]:
data=pd.read_csv("DigitalAd.csv")

In [25]:
data.head(5)

Age  Salary  Status
0   45  120554       1
1   49  356341       1
2   49  412002       1
3   25  577537       0
4   34  393379       1

In [27]:
data.shape

(529, 3)

In [30]:
x= data.iloc[:,:-1].values

In [31]:
x

array([[    45, 120554],
       [    49, 356341],
       [    49, 412002],
       ...,
       [    18, 220050],
       [    39, 275289],
       [    30, 118094]], dtype=int64)

In [34]:
y=data.iloc[:,-1].values

In [35]:
y

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,

## Spliting the dataset Train and Test

In [36]:
!pip install scikit_learn

Defaulting to user installation because normal site-packages is not writeable


In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size = 0.25,random_state=0)

## Feature Scaling

Since both the features have different scale, there is a chance that higher magnitude. This will impact the performance of the machine learning algoritham and obviously,we do not want our algoritham to be biased towards one feature.

In [39]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train =sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)

[[-5.84396864e-01  1.52716254e+00]
 [ 8.86277768e-01 -5.43622666e-01]
 [-4.79348676e-01  6.65284291e-01]
 [-1.73992693e+00  6.36813856e-01]
 [-7.94493240e-01  7.37483183e-01]
 [-1.63487874e+00  7.60517985e-01]
 [-1.31973418e+00 -1.12689861e+00]
 [-4.79348676e-01 -1.21713709e+00]
 [-1.52983056e+00 -1.44138885e+00]
 [ 8.86277768e-01 -2.21709140e-01]
 [-5.91559241e-02 -9.91940754e-01]
 [ 1.09637414e+00  1.17032884e+00]
 [-4.79348676e-01  1.39257556e+00]
 [-1.52983056e+00  3.71302272e-01]
 [ 6.76181392e-01  6.18507708e-01]
 [ 3.61036828e-01 -1.59067755e+00]
 [-1.21468599e+00 -3.22616585e-02]
 [ 7.81229580e-01 -6.61398593e-01]
 [ 4.66085016e-01  8.50571021e-01]
 [ 1.30647052e+00 -1.34196543e+00]
 [ 1.41151871e+00  1.15390604e+00]
 [-8.99541429e-01 -2.53772425e-01]
 [ 1.62161508e+00 -8.65066805e-01]
 [ 1.41151871e+00  1.02110916e-01]
 [ 4.58922640e-02  5.67976017e-01]
 [ 5.71133204e-01 -9.81063692e-01]
 [-7.94493240e-01  1.02442438e+00]
 [ 1.20142233e+00  1.26403215e-01]
 [-2.69252300e-01 -1

## Training

In [42]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

## Predicting , wheathr new customer with Age &salary will Buy or Not

In [47]:
age =int(input("Enter New customer's Age"))
sal= int(input("Enter New customer's Salary"))
newCust =[[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result ==1:
    print("customer will Buy")
else:
    print("customet won't Buy")

Enter New customer's Age45
Enter New customer's Salary45000
[1]
customer will Buy


## Prediction for all Test Data

In [43]:
y_pred = model.predict(x_test)

In [44]:
y_pred 

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score
print("Accuracy of the model : {0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the model : 47.368421052631575%
